name: flutter_edge_guard
description: Understand and fix modern Android edge-to-edge UI problems. An edge-to-edge protection layer and diagnostics engine for Flutter.
version: 0.2.0
homepage: https://github.com/abhi9827/flutter_edge_guard
repository: https://github.com/abhi9827/flutter_edge_guard
issue_tracker: https://github.com/abhi9827/flutter_edge_guard/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

executables:
  doctor: doctor

topics:
  - android
  - edge-to-edge
  - diagnostics
  - safearea

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.0

