import 'edge_guard_issue.dart';
import 'edge_guard_platform_info.dart';
import 'edge_insets_info.dart';

/// The complete diagnostic report generated by the EdgeGuard diagnostics engine.
class EdgeGuardReport {
  /// ISO 8601 timestamp of when the report was generated.
  final String timestamp;

  /// Detected platform information and capabilities.
  final EdgeGuardPlatformInfo platformInfo;

  /// Detailed inset information captured at the time of the report.
  final EdgeInsetsInfo insetsInfo;

  /// A list of potential or confirmed issues discovered.
  final List<EdgeGuardIssue> issues;

  const EdgeGuardReport({
    required this.timestamp,
    required this.platformInfo,
    required this.insetsInfo,
    required this.issues,
  });

  /// Serializes the entire report into a deterministic JSON representation.
  Map<String, dynamic> toJson() {
    return {
      'timestamp': timestamp,
      'platformInfo': platformInfo.toJson(),
      'insetsInfo': insetsInfo.toJson(),
      'issues': issues.map((i) => i.toJson()).toList(),
    };
  }

  @override
  String toString() {
    final buffer = StringBuffer();
    buffer.writeln('EDGE GUARD REPORT');
    buffer.writeln('=================');
    buffer.writeln('Timestamp: $timestamp');
    buffer.writeln('');

    buffer.writeln('PLATFORM');
    buffer.writeln('--------');
    buffer.writeln('Platform: ${platformInfo.platform}');
    buffer.writeln('Android SDK: ${platformInfo.androidSdkInt ?? 'Unknown'}');
    buffer.writeln('Navigation Mode: ${platformInfo.navigationMode.name}');
    buffer.writeln('Large Screen: ${platformInfo.isLargeScreen}');
    buffer.writeln('Foldable: ${platformInfo.isFoldable}');
    buffer.writeln('');

    buffer.writeln('INSETS');
    buffer.writeln('------');
    buffer.writeln('Edge-to-Edge: ${insetsInfo.isEdgeToEdge}');
    buffer.writeln('Keyboard Visible: ${insetsInfo.keyboardVisible}');
    buffer.writeln(
      'Window Size: ${insetsInfo.windowSize.width} x ${insetsInfo.windowSize.height}',
    );
    buffer.writeln('Orientation: ${insetsInfo.orientation.name}');
    buffer.writeln('');

    buffer.writeln('Status Bars: ${insetsInfo.statusBars}');
    buffer.writeln('Navigation Bars: ${insetsInfo.navigationBars}');
    buffer.writeln('System Gestures: ${insetsInfo.systemGestures}');
    buffer.writeln(
      'Mandatory System Gestures: ${insetsInfo.mandatorySystemGestures}',
    );
    buffer.writeln('Tappable Element: ${insetsInfo.tappableElement}');
    buffer.writeln('IME: ${insetsInfo.ime}');
    buffer.writeln('Display Cutout: ${insetsInfo.displayCutout}');
    buffer.writeln('');

    buffer.writeln('ISSUES DETECTED: ${issues.length}');
    buffer.writeln('--------------------');
    for (final issue in issues) {
      buffer.writeln(issue.toString());
      buffer.writeln('---');
    }

    return buffer.toString();
  }
}
